##내 풀이

In [12]:
tup=("SUN","MON", "TUE", "WED", "THU", "FRI", "SAT")
date={1:31, 3:31, 5:31, 7:31, 8:31, 10:31, 12:31, 4:30, 6:30, 9:30, 11:30,2:28}
month, day=map(int, input().split())
sum=day
for i in range(month-1):
  sum+=date[i+1]
sum=result%7
print(tup[sum])

12 31
MON

##다른사람 풀이

In [11]:
from calendar import weekday
l=['MON','TUE','WED','THU','FRI','SAT','SUN']
d = weekday(2007,*map(int,input().split()))
print(l[d])

1 1
MON

**calendar.weekday(year, month, day)**

year (1970--...), month (1--12), day (1--31)의 요일(0은 월요일)을 반환합니다.